-- 0003_stage3_cashflow (stage-3.md §3.1). The CREATE statements were generated by drizzle-kit
-- (pnpm --filter @joinr/server db:generate --name stage3_cashflow); the three data statements at the
-- end were appended by hand. They convert a database that already holds imported data: one balance
-- entry per cash account (D58), and the side-income period entries become dated deposits (D57).
CREATE TABLE `cash_balance_entries` (
	`id` integer PRIMARY KEY NOT NULL,
	`account_id` integer NOT NULL,
	`as_of` text NOT NULL,
	`balance_cents` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`account_id`) REFERENCES `cash_accounts`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `cash_balance_entries_account_idx` ON `cash_balance_entries` (`account_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `cash_balance_entries_account_id_as_of_unique` ON `cash_balance_entries` (`account_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `savings_adjustments` (
	`id` integer PRIMARY KEY NOT NULL,
	`period_month` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`note` text NOT NULL,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `savings_adjustments_period_month_unique` ON `savings_adjustments` (`period_month`);--> statement-breakpoint
CREATE TABLE `savings_goals` (
	`id` integer PRIMARY KEY NOT NULL,
	`name` text NOT NULL,
	`target_cents` integer NOT NULL,
	`target_date` text,
	`sort_order` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text
);
--> statement-breakpoint
CREATE TABLE `side_income_deposits` (
	`id` integer PRIMARY KEY NOT NULL,
	`stream_id` integer NOT NULL,
	`deposit_date` text NOT NULL,
	`amount_cents` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`stream_id`) REFERENCES `income_streams`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `side_income_deposits_date_idx` ON `side_income_deposits` (`deposit_date`);--> statement-breakpoint
CREATE INDEX `side_income_deposits_stream_idx` ON `side_income_deposits` (`stream_id`);--> statement-breakpoint
CREATE TABLE `dividend_events` (
	`instrument_id` integer NOT NULL,
	`ex_date` text NOT NULL,
	`amount_per_unit` text NOT NULL,
	`currency` text NOT NULL,
	`close_before_ex` text,
	`close_date` text,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	`dismissed_at` text,
	PRIMARY KEY(`instrument_id`, `ex_date`),
	FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
-- Hand-written data statements (not generated). Converted rows keep origin and sheet_ref, so a
-- database with no app rows still has no app data after the upgrade.
INSERT INTO `cash_balance_entries` (`account_id`, `as_of`, `balance_cents`, `note`, `origin`, `sheet_ref`)
  SELECT `id`, COALESCE(`balance_as_of`, date('now')), `balance_cents`, NULL, `origin`, `sheet_ref`
  FROM `cash_accounts` ORDER BY `id`;
--> statement-breakpoint
-- A deposit is dated at its period end (the month end when unknown), but never after the imported
-- as-of (the latest balance_as_of); a zero amount carries no information and is skipped.
INSERT INTO `side_income_deposits` (`stream_id`, `deposit_date`, `amount_cents`, `note`, `origin`, `sheet_ref`)
  SELECT `stream_id`,
         MIN(COALESCE(`period_end`, date(`period_month` || '-01', '+1 month', '-1 day')),
             COALESCE((SELECT MAX(`balance_as_of`) FROM `cash_accounts`), '9999-12-31')),
         `amount_cents`, NULL, `origin`, `sheet_ref`
  FROM `side_income_entries` WHERE `amount_cents` <> 0 ORDER BY `period_month`, `stream_id`, `id`;
--> statement-breakpoint
-- side_income_entries stays (append-only) but is never written again.
DELETE FROM `side_income_entries`;
