-- 0004_stage4_assets (stage-4.md §3.1). The CREATE and ALTER statements were generated by drizzle-kit
-- (pnpm --filter @joinr/server db:generate --name stage4_assets); the data statements at the end were
-- appended by hand. They convert a database that already holds imported data: a price entry per
-- manual other asset (D72), the imported contribution dates, a balance entry per super fund (D69),
-- the History-derived contributions, a valuation per property and a balance entry per loan (D66).
CREATE TABLE `loan_balance_entries` (
	`id` integer PRIMARY KEY NOT NULL,
	`loan_id` integer NOT NULL,
	`as_of` text NOT NULL,
	`balance_cents` integer NOT NULL,
	`repayments_cents` integer,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`loan_id`) REFERENCES `loans`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `loan_balance_entries_loan_idx` ON `loan_balance_entries` (`loan_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `loan_balance_entries_loan_id_as_of_unique` ON `loan_balance_entries` (`loan_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `loan_offset_links` (
	`account_id` integer PRIMARY KEY NOT NULL,
	`loan_id` integer NOT NULL,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`account_id`) REFERENCES `cash_accounts`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`loan_id`) REFERENCES `loans`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `loan_offset_links_loan_idx` ON `loan_offset_links` (`loan_id`);--> statement-breakpoint
CREATE TABLE `other_asset_prices` (
	`id` integer PRIMARY KEY NOT NULL,
	`other_asset_id` integer NOT NULL,
	`as_of` text NOT NULL,
	`unit_price` text NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`other_asset_id`) REFERENCES `other_assets`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `other_asset_prices_asset_idx` ON `other_asset_prices` (`other_asset_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `other_asset_prices_other_asset_id_as_of_unique` ON `other_asset_prices` (`other_asset_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `other_asset_sales` (
	`id` integer PRIMARY KEY NOT NULL,
	`other_asset_id` integer NOT NULL,
	`sale_date` text NOT NULL,
	`units` text NOT NULL,
	`proceeds_cents` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`other_asset_id`) REFERENCES `other_assets`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `other_asset_sales_asset_idx` ON `other_asset_sales` (`other_asset_id`);--> statement-breakpoint
CREATE TABLE `property_valuations` (
	`id` integer PRIMARY KEY NOT NULL,
	`property_id` integer NOT NULL,
	`as_of` text NOT NULL,
	`value_cents` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `property_valuations_property_idx` ON `property_valuations` (`property_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `property_valuations_property_id_as_of_unique` ON `property_valuations` (`property_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `super_balance_entries` (
	`id` integer PRIMARY KEY NOT NULL,
	`fund_id` integer NOT NULL,
	`as_of` text NOT NULL,
	`balance_cents` integer NOT NULL,
	`transfer_in_cents` integer,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text,
	FOREIGN KEY (`fund_id`) REFERENCES `super_funds`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE INDEX `super_balance_entries_fund_idx` ON `super_balance_entries` (`fund_id`);--> statement-breakpoint
CREATE UNIQUE INDEX `super_balance_entries_fund_id_as_of_unique` ON `super_balance_entries` (`fund_id`,`as_of`);--> statement-breakpoint
CREATE TABLE `super_sg_overrides` (
	`id` integer PRIMARY KEY NOT NULL,
	`period_month` text NOT NULL,
	`gross_cents` integer NOT NULL,
	`note` text,
	`origin` text DEFAULT 'app' NOT NULL,
	`sheet_ref` text
);
--> statement-breakpoint
CREATE UNIQUE INDEX `super_sg_overrides_period_month_unique` ON `super_sg_overrides` (`period_month`);--> statement-breakpoint
CREATE TABLE `market_quote_history` (
	`series_id` text NOT NULL,
	`date` text NOT NULL,
	`value` text NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	PRIMARY KEY(`series_id`, `date`)
);
--> statement-breakpoint
ALTER TABLE `other_assets` ADD `purchase_fx_rate` text;--> statement-breakpoint
ALTER TABLE `other_assets` ADD `purchase_fx_source` text;--> statement-breakpoint
ALTER TABLE `other_assets` ADD `purchase_fx_date` text;--> statement-breakpoint
ALTER TABLE `super_funds` ADD `receives_sg` integer DEFAULT false NOT NULL;
--> statement-breakpoint
-- Hand-written data statements (not generated). Each derived row keeps its parent's origin and
-- sheet_ref, so a database with no app rows still has no app data after the upgrade.
-- A manual other asset with a price gets its first price entry (D72); a negative price gets none
-- (a price entry is never negative; the importer skips it the same way).
INSERT INTO `other_asset_prices` (`other_asset_id`, `as_of`, `unit_price`, `note`, `origin`, `sheet_ref`)
  SELECT `id`, COALESCE(`unit_price_as_of`, date('now')), `unit_price`, NULL, `origin`, `sheet_ref`
  FROM `other_assets` WHERE `price_source` = 'manual' AND `unit_price` IS NOT NULL AND `unit_price` NOT LIKE '-%' ORDER BY `id`;
--> statement-breakpoint
-- The imported contribution of the live month is dated at min(month end, workbook as-of), the
-- workbook as-of being the latest applied import run's (else the latest fund, then cash, balance date).
UPDATE `super_entries`
  SET `entry_date` = MIN(date(`period_month` || '-01', '+1 month', '-1 day'),
                         COALESCE((SELECT `workbook_as_of` FROM `import_runs`
                                     WHERE `status` = 'succeeded' AND `dry_run` = 0 AND `workbook_as_of` IS NOT NULL
                                     ORDER BY `started_at` DESC LIMIT 1),
                                  (SELECT MAX(`balance_as_of`) FROM `super_funds`),
                                  (SELECT MAX(`balance_as_of`) FROM `cash_accounts`), '9999-12-31'))
  WHERE `kind` = 'voluntary_contribution' AND `entry_date` IS NULL;
--> statement-breakpoint
-- One balance entry per fund, dated at the latest snapshot's run date when the funds' total equals
-- its History Q (nothing was updated since), else at the fund's balance date.
INSERT INTO `super_balance_entries` (`fund_id`, `as_of`, `balance_cents`, `transfer_in_cents`, `note`, `origin`, `sheet_ref`)
  SELECT f.`id`,
         CASE WHEN (SELECT SUM(`balance_cents`) FROM `super_funds` WHERE `archived` = 0)
                   = (SELECT `super_value_cents` FROM `snapshots` ORDER BY `run_date` DESC LIMIT 1)
              THEN (SELECT `run_date` FROM `snapshots` ORDER BY `run_date` DESC LIMIT 1)
              ELSE COALESCE(f.`balance_as_of`, date('now')) END,
         f.`balance_cents`, NULL, NULL, f.`origin`, f.`sheet_ref`
  FROM `super_funds` f ORDER BY f.`id`;
--> statement-breakpoint
-- The fund's balance date follows its entry (the denormalised copy).
UPDATE `super_funds` SET `balance_as_of` =
  (SELECT MAX(e.`as_of`) FROM `super_balance_entries` e WHERE e.`fund_id` = `super_funds`.`id`);
--> statement-breakpoint
-- One contribution per migrated snapshot with a non-zero History R, dated at its run date.
INSERT INTO `super_entries` (`period_month`, `kind`, `fund_id`, `entry_date`, `amount_cents`, `note`, `origin`, `sheet_ref`)
  SELECT s.`period_month`, 'voluntary_contribution', NULL, s.`run_date`, s.`super_contrib_cents`, NULL, s.`origin`,
         'History!R' || substr(s.`sheet_ref`, 10)
  FROM `snapshots` s
  WHERE s.`source` = 'migrated' AND s.`sheet_ref` LIKE 'History!A%'
    AND s.`super_contrib_cents` IS NOT NULL AND s.`super_contrib_cents` <> 0
    AND NOT EXISTS (SELECT 1 FROM `super_entries` e WHERE e.`sheet_ref` = 'History!R' || substr(s.`sheet_ref`, 10))
  ORDER BY s.`run_date`;
--> statement-breakpoint
-- One valuation per property, at its valuation date.
INSERT INTO `property_valuations` (`property_id`, `as_of`, `value_cents`, `note`, `origin`, `sheet_ref`)
  SELECT `id`, COALESCE(`valuation_date`, date('now')), `current_value_cents`, NULL, `origin`, `sheet_ref`
  FROM `properties` ORDER BY `id`;
--> statement-breakpoint
-- One balance entry per loan (its current balance; the start fields give the log's start point),
-- dated at the latest snapshot's run date when the property loans' total equals its |AB| and the
-- loan started before it, else at the loan's balance date.
INSERT INTO `loan_balance_entries` (`loan_id`, `as_of`, `balance_cents`, `repayments_cents`, `note`, `origin`, `sheet_ref`)
  SELECT l.`id`,
         CASE WHEN l.`property_id` IS NOT NULL
                   AND (SELECT SUM(`current_balance_cents`) FROM `loans` WHERE `property_id` IS NOT NULL)
                       = -(SELECT `mortgage_balance_cents` FROM `snapshots` ORDER BY `run_date` DESC LIMIT 1)
                   AND (l.`start_date` IS NULL
                        OR l.`start_date` < (SELECT `run_date` FROM `snapshots` ORDER BY `run_date` DESC LIMIT 1))
              THEN (SELECT `run_date` FROM `snapshots` ORDER BY `run_date` DESC LIMIT 1)
              ELSE COALESCE(l.`balance_as_of`, date('now')) END,
         l.`current_balance_cents`, NULL, NULL, l.`origin`, l.`sheet_ref`
  FROM `loans` l ORDER BY l.`id`;
--> statement-breakpoint
-- The loan's balance date follows its entry (the denormalised copy).
UPDATE `loans` SET `balance_as_of` =
  (SELECT MAX(e.`as_of`) FROM `loan_balance_entries` e WHERE e.`loan_id` = `loans`.`id`);
