-- 0005_stage5_history (stage-5.md §3.1). The CREATE and ALTER statements were generated by drizzle-kit
-- (pnpm --filter @joinr/server db:generate --name stage5_history); the trigger at the end was appended
-- by hand after a statement breakpoint. No data statement: migrated rows keep every imported value and
-- the new snapshot columns stay null (revision 0).
CREATE TABLE `snapshot_audit` (
	`id` integer PRIMARY KEY NOT NULL,
	`period_month` text NOT NULL,
	`snapshot_id` integer,
	`action` text NOT NULL,
	`trigger` text NOT NULL,
	`at` text NOT NULL,
	`changes_json` text,
	`snapshot_json` text,
	`note` text,
	`detail_json` text
);
--> statement-breakpoint
CREATE INDEX `snapshot_audit_period_idx` ON `snapshot_audit` (`period_month`);--> statement-breakpoint
ALTER TABLE `snapshots` ADD `offset_cents` integer;--> statement-breakpoint
ALTER TABLE `snapshots` ADD `mortgage_offset_cents` integer;--> statement-breakpoint
ALTER TABLE `snapshots` ADD `cash_debt_cents` integer;--> statement-breakpoint
ALTER TABLE `snapshots` ADD `super_measured_through` text;--> statement-breakpoint
ALTER TABLE `snapshots` ADD `note` text;--> statement-breakpoint
ALTER TABLE `snapshots` ADD `revision` integer DEFAULT 0 NOT NULL;--> statement-breakpoint
-- Hand-written: the identity of a snapshot never changes; corrections change figures only.
CREATE TRIGGER `snapshots_identity_immutable` BEFORE UPDATE OF `run_date`, `period_month`, `source`, `recorded_at` ON `snapshots`
BEGIN SELECT RAISE(ABORT, 'snapshot identity is immutable'); END;
