-- 0006_stage9_mobile (stage-9.md §3.1, §3.1a, §3.2). Generated by drizzle-kit (pnpm --filter @joinr/server
-- db:generate --name stage9_mobile). Three DDL changes and no data statement: the two day caches start
-- empty and the two market_quotes columns stay null until the next price refresh.
CREATE TABLE `day_quotes` (
	`instrument_id` integer PRIMARY KEY NOT NULL,
	`session_date` text NOT NULL,
	`time_zone` text NOT NULL,
	`granularity` text NOT NULL,
	`native_currency` text NOT NULL,
	`previous_close` text,
	`regular_start` text,
	`regular_end` text,
	`points` text DEFAULT '[]' NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `series_day_quotes` (
	`series_id` text PRIMARY KEY NOT NULL,
	`session_date` text NOT NULL,
	`time_zone` text NOT NULL,
	`granularity` text NOT NULL,
	`native_currency` text NOT NULL,
	`previous_close` text,
	`regular_start` text,
	`regular_end` text,
	`points` text DEFAULT '[]' NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL
);
--> statement-breakpoint
ALTER TABLE `market_quotes` ADD `previous_close` text;--> statement-breakpoint
ALTER TABLE `market_quotes` ADD `previous_close_date` text;
