-- 0007_stage10_closes (stage-10.md §3.1–§3.4). Generated by drizzle-kit (pnpm --filter @joinr/server
-- db:generate --name stage10_closes). The three CREATE TABLEs only and no data statement: the closes
-- caches start empty and the closes job fills them (§5).
CREATE TABLE `instrument_closes` (
	`instrument_id` integer NOT NULL,
	`date` text NOT NULL,
	`close` text NOT NULL,
	`currency` text NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	PRIMARY KEY(`instrument_id`, `date`),
	FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `instrument_splits` (
	`instrument_id` integer NOT NULL,
	`date` text NOT NULL,
	`numerator` text NOT NULL,
	`denominator` text NOT NULL,
	`fetched_at` text NOT NULL,
	PRIMARY KEY(`instrument_id`, `date`),
	FOREIGN KEY (`instrument_id`) REFERENCES `instruments`(`id`) ON UPDATE no action ON DELETE cascade
);
--> statement-breakpoint
CREATE TABLE `series_closes` (
	`series_id` text NOT NULL,
	`date` text NOT NULL,
	`value` text NOT NULL,
	`source` text NOT NULL,
	`fetched_at` text NOT NULL,
	PRIMARY KEY(`series_id`, `date`)
);
